baseurl      = "https://pxlwrk.de"
title        = "PXLWRK"
languageCode = "de-de"
theme        = "hello-friend-ng"

defaultContentLanguage = "de"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = true
disable404     = false
disableHugoGeneratorInject = false

lastModDisplay = "[your display text]"

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Andre Geier"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]
  dateform        = "02. January 2006"
  dateformShort   = "2. Jan"
  dateformNum     = "02.01.2006"
  dateformNumTime = "02.01.2006 15:04"

  # Metadata mostly used in document's head
  # 
  description = "agentur für sensitive digitalisierung"
  keywords = "digitalisierung"
  images = [""]

  # Home subtitle of the index page.
  #
  homeSubtitle = "wir entwickeln lösungen"

  # Set a background for the homepage
  # backgroundImage = "assets/images/background.jpg"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  #
  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  #
  disableReadOtherPosts = false

  # Enable theme toggle
  # 
  # This options enables the theme toggle for the theme. 
  # Per default, this option is off. 
  # The theme is respecting the prefers-color-scheme of the operating systeme. 
  # With this option on, the page user is able to set the scheme he wants. 
  enableThemeToggle = true

  # Sharing buttons
  #
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  #
  enableSharingButtons = true

  # Global language menu
  #
  # Enables the global language menu.
  #
  enableGlobalLanguageMenu = false

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  #
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  #
  justifyContent = false  # Set "text-align: justify" to .post-content.

  # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  [params.footer]
    trademark = false
    rss = false
    copyright = false
    author = false

    bottomText = ["Made with &#10084; in Berlin"]
    topText = ['<a href="/imprint">Impressum</a>','<a href="https://calendly.com/pxlwrk">Termin vereinbaren</a>']

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = "$"
    logoText     = " press:start"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
     logoCursorColor    = "#7af57a"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"

  # Commento is more than just a comments widget you can embed — 
  # it’s a return to the roots of the internet. 
  # An internet without the tracking and invasions of privacy. 
  # An internet that is simple and lightweight. 
  # An internet that is focused on interesting discussions, not ads. 
  # A better internet.
  # Uncomment this to enable Commento.
  #
  # [params.commento]
  #   url = ""

  # Uncomment this if you want a portrait on your start page
  #
  [params.portrait]
     path     = "/images/logo-squared.jpg"
     alt      = "André Geier"
     maxWidth = "200px"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/distantbit"

  [[params.social]]
    name = "email"
    url  = "mailto:hallo@pxlwrk.de"

  [[params.social]]
    name = "github"
    url  = "https://github.com/distantbit"

  [[params.social]]
    name = "threema"
    url  = "https://threema.id/86PSWXB5"

[languages]
  [languages.en]
    subtitle  = "we develop solutions"
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.de]
    subtitle  = "wir entwickeln lösungen"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "we"
    name       = "./Wir"
    url        = "we/"
    weight     = 1
  [[menu.main]]
    identifier = "develop"
    name       = "./Entwickeln"
    url        = "develop/"
    weight     = 2
  [[menu.main]]
    identifier = "solutions"
    name       = "./Lösungen"
    url        = "solutions/"
    weight     = 3
  [[menu.main]]
    identifier = "blog"
    name       = "../Blog"
    url        = "https://blog.pxlwrk.de"
    weight     = 9